version: 1
robot_name: thais
passive_urdf_joints:
  - i01.head.eyeLeft.001_link_joint
  - i01.head.eyeLeft_link_joint
  - i01.head.eyeRight.001_link_joint
  - i01.head.eyeRight_link_joint
  - i01.head.jaw_link_joint
  - i01.head.neck.001_link_joint
  - i01.head.rollNeck_link_joint
  - i01.head.rothead_link_joint
  - i01.leftHand.index_link_joint
  - i01.leftHand.majeure_link_joint
  - i01.leftHand.pinky_link_joint
  - i01.leftHand.ringFinger_link_joint
  - i01.leftHand.thumb_link_joint
  - i01.torso.midStom_link_joint
  - i01.torso.topStom_link_joint
  - left_elbow_x_link_joint
  - left_shoulder_x_link_joint
  - left_shoulder_y_link_joint
  - left_shoulder_z_link_joint
  - left_wrist_z_link_joint
  - right_shoulder_y_link_joint
ignore_urdf_joints:
  - Empty.001_link_joint
  - Empty.002_link_joint
  - i01.leftHand.index2_link_joint
  - i01.leftHand.index3_link_joint
  - i01.leftHand.majeure2_link_joint
  - i01.leftHand.majeure3_link_joint
  - i01.leftHand.pinky0_link_joint
  - i01.leftHand.pinky2_link_joint
  - i01.leftHand.pinky3_link_joint
  - i01.leftHand.ringfinger0_link_joint
  - i01.leftHand.ringfinger2_link_joint
  - i01.leftHand.ringfinger3_link_joint
  - i01.leftHand.thumb1_link_joint
  - i01.leftHand.thumb3_link_joint
  - i01.leftHand.wrist.001_link_joint
  - i01.rightHand.index2_link_joint
  - i01.rightHand.index3_link_joint
  - i01.rightHand.majeure2_link_joint
  - i01.rightHand.majeure3_link_joint
  - i01.rightHand.pinky0_link_joint
  - i01.rightHand.pinky2_link_joint
  - i01.rightHand.pinky3_link_joint
  - i01.rightHand.ringfinger0_link_joint
  - i01.rightHand.ringfinger2_link_joint
  - i01.rightHand.ringfinger3_link_joint
  - i01.rightHand.thumb1_link_joint
  - i01.rightHand.thumb3_link_joint
  - i01.rightHand.wrist.001_link_joint
firmware:
  source_dir: micro_ros_raspberrypi_pico_sdk
  build_dir: build
controller_manager:
  update_rate: 100
boards:
  rp2040_left_arm:
    serial_id: E6617C93E3858429
    board_class: internal_servo_only
    internal_servo_slots: 18
    firmware_target: pico_micro_ros_left_arm
    compile_definition: USE_LEFT_ARM
    topic_actuators: actuators/left_arm
    topic_sensors: sensors/left_arm
    controller:
      name: left_arm_controller
      type: joint_trajectory_controller/JointTrajectoryController
  rp2040_right_arm:
    serial_id: E6617C93E37A6629
    board_class: internal_servo_only
    internal_servo_slots: 18
    firmware_target: pico_micro_ros_right_arm
    compile_definition: USE_RIGHT_ARM
    topic_actuators: actuators/right_arm
    topic_sensors: sensors/right_arm
    controller:
      name: right_arm_controller
      type: joint_trajectory_controller/JointTrajectoryController
  rp2040_torso_head:
    serial_id: ''
    board_class: internal_servo_i2c_pwm
    internal_servo_slots: 16
    firmware_target: pico_micro_ros_torso
    compile_definition: USE_TORSO
    topic_actuators: actuators/torso
    topic_sensors: sensors/torso
    controller:
      name: torso_head_controller
      type: joint_trajectory_controller/JointTrajectoryController
actuators:
  - id: right_shoulder_z
    urdf_joint: right_shoulder_z_link_joint
    board: rp2040_right_arm
    virtual_pin: 0
    physical_pin: 10
    servo_type: '270'
    offset_deg: 0
    direction: 1
    scale: 1
    servo_min_deg: 155
    servo_max_deg: 165
    servo_default_deg: 160
    enabled: true
  - id: right_shoulder_x
    urdf_joint: right_shoulder_x_link_joint
    board: rp2040_right_arm
    virtual_pin: 1
    physical_pin: 11
    servo_type: '270'
    offset_deg: 0
    direction: 1
    scale: 1
    servo_min_deg: 140
    servo_max_deg: 180
    servo_default_deg: 180
    enabled: true
  - id: right_elbow
    urdf_joint: right_elbow
    board: rp2040_right_arm
    virtual_pin: 2
    physical_pin: 12
    servo_type: '270'
    offset_deg: 0
    direction: 1
    scale: 1
    servo_min_deg: 100
    servo_max_deg: 110
    servo_default_deg: 100
    enabled: true
  - id: right_wrist_z
    urdf_joint: right_wrist_z_link_joint
    board: rp2040_right_arm
    virtual_pin: 3
    physical_pin: 13
    servo_type: '300'
    offset_deg: 0
    direction: 1
    scale: 1
    servo_min_deg: 0
    servo_max_deg: 230
    servo_default_deg: 150
    enabled: true
  - id: right_thumb
    urdf_joint: i01.rightHand.thumb_link_joint
    board: rp2040_right_arm
    virtual_pin: 4
    physical_pin: 14
    servo_type: '300'
    offset_deg: 0
    direction: 1
    scale: 1
    servo_min_deg: 36
    servo_max_deg: 150
    servo_default_deg: 36
    enabled: true
  - id: right_index
    urdf_joint: i01.rightHand.index_link_joint
    board: rp2040_right_arm
    virtual_pin: 5
    physical_pin: 15
    servo_type: '300'
    offset_deg: 0
    direction: 1
    scale: 1
    servo_min_deg: 16
    servo_max_deg: 150
    servo_default_deg: 16
    enabled: true
  - id: right_middle
    urdf_joint: i01.rightHand.majeure_link_joint
    board: rp2040_right_arm
    virtual_pin: 6
    physical_pin: 16
    servo_type: '300'
    offset_deg: 0
    direction: 1
    scale: 1
    servo_min_deg: 21
    servo_max_deg: 150
    servo_default_deg: 21
    enabled: true
  - id: right_ring
    urdf_joint: i01.rightHand.ringFinger_link_joint
    board: rp2040_right_arm
    virtual_pin: 7
    physical_pin: 17
    servo_type: '300'
    offset_deg: 0
    direction: 1
    scale: 1
    servo_min_deg: 33
    servo_max_deg: 150
    servo_default_deg: 33
    enabled: true
  - id: right_pinky
    urdf_joint: i01.rightHand.pinky_link_joint
    board: rp2040_right_arm
    virtual_pin: 8
    physical_pin: 18
    servo_type: '300'
    offset_deg: 0
    direction: 1
    scale: 1
    servo_min_deg: 30
    servo_max_deg: 150
    servo_default_deg: 30
    enabled: true
sensors:
  - id: right_thumb_pressure
    type: pressure
    associated_actuator: right_thumb
    board: rp2040_right_arm
    virtual_pin: 0
    physical_pin: 16
    min_value: null
    max_value: null
    enabled: false
  - id: right_index_pressure
    type: pressure
    associated_actuator: right_index
    board: rp2040_right_arm
    virtual_pin: 1
    physical_pin: 17
    min_value: null
    max_value: null
    enabled: false
  - id: right_middle_pressure
    type: pressure
    associated_actuator: right_middle
    board: rp2040_right_arm
    virtual_pin: 2
    physical_pin: 18
    min_value: null
    max_value: null
    enabled: false
  - id: right_ring_pressure
    type: pressure
    associated_actuator: right_ring
    board: rp2040_right_arm
    virtual_pin: 3
    physical_pin: 19
    min_value: null
    max_value: null
    enabled: false
  - id: right_pinky_pressure
    type: pressure
    associated_actuator: right_pinky
    board: rp2040_right_arm
    virtual_pin: 4
    physical_pin: 20
    min_value: null
    max_value: null
    enabled: false
