- ros_topic_name: "/clock"
  gz_topic_name: "/world/default/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera/gazebo/raw"
  gz_topic_name: "/world/default/camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/sensor_right_arm/mock_sensor_data"
  gz_topic_name: "/sensor_right_arm/mock_sensor_data"
  ros_type_name: "ros_gz_interfaces/msg/Float32Array"
  gz_type_name: "gz.msgs.Float_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/sensor_left_arm/mock_sensor_data"
  gz_topic_name: "/sensor_left_arm/mock_sensor_data"
  ros_type_name: "ros_gz_interfaces/msg/Float32Array"
  gz_type_name: "gz.msgs.Float_V"
  direction: GZ_TO_ROS
